### ISSUE TITLE
Additional release version of the pdf with all content in the same orientation

### ISSUE THREAD

**Issue by sasjafor** [dotSp0T/Anno_1800_Chains_Consumption#2]
I really love the work and it is really useful, but one thing that would make it a lot easier to use on a second screen for example, would be a rendered pdf with all the production chains displayed horizontally. Otherwise, I need to tilt my head or rotate the pdf.
Or alternatively, just make everything the same orientation, then I can just rotate the pdf in acrobat, but now I need to pick between viewing building and ship chains and the rest.

**Comment by dotSp0T** [comment]
working on it

**Comment by dotSp0T** [comment]
Resolved with 0671440581fc9c7aed5b267c21587309dcffe1d0

**Comment by sasjafor** [comment]
Awesome, thx!

**Comment by rkost** [comment]
Nice, thank you!
